<a href="https://colab.research.google.com/github/DepartmentOfStatisticsPUE/air-2022/blob/main/notebooks/5_obliczenia_macierzowe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Rozwiązujemy zadania z pliku `numpy-jezyk-macierzowy.pdf`. Zaczniemy od zadania nr 1.

$$
A = 
\begin{pmatrix}
1 & 2 & -1 & 0 \\
3 & −2 &  4  & 5 \\ 
2  & 6  & 5  & −3 \\
0  & 1 & 5  & −4
\end{pmatrix}
$$

$$
B = 
\begin{pmatrix}
3 & 6 \\
4 & 0 \\
2 & −1 \\
1 & 1
\end{pmatrix}
$$

1. Oblicz wyznacznik macierzy A.
2. Znajdź iloczyn A · B.
3. Znajdź macierz transponowaną $B^T$
4. Znajdź macierz odwrotną $A^{−1}$
5. Znajdź $A^3$

In [ ]:
A = np.array( [ (1, 2, -1, 0), (3, -2, 4, 5), (2, 6, 5, -3), (0, 1, 5, -4) ] )
B = np.array( [ (3, 6), (4, 0), (2, -1), (1, 1) ] )
B

array([[ 3,  6],
       [ 4,  0],
       [ 2, -1],
       [ 1,  1]])

Rozwiązanie 1.1

In [ ]:
np.linalg.det(A)

154.00000000000006

Rozwiązanie 1.2

In [ ]:
A @ B ## tylko w pythonie w wersji 3 i wyżej

array([[ 9,  7],
       [14, 19],
       [37,  4],
       [10, -9]])

In [ ]:
np.matmul(A, B) ## matrix multiplication

array([[ 9,  7],
       [14, 19],
       [37,  4],
       [10, -9]])

In [ ]:
A.dot(B)

array([[ 9,  7],
       [14, 19],
       [37,  4],
       [10, -9]])

Rozwiązanie 1.3 

In [ ]:
B.T

array([[ 3,  4,  2,  1],
       [ 6,  0, -1,  1]])

In [ ]:
B.transpose()

array([[ 3,  4,  2,  1],
       [ 6,  0, -1,  1]])

In [ ]:
np.transpose(B)

array([[ 3,  4,  2,  1],
       [ 6,  0, -1,  1]])

Rozwiązanie 1.4

In [ ]:
np.linalg.inv(A)

array([[ 1.42207792,  0.2012987 , -0.51298701,  0.63636364],
       [-0.43506494, -0.08441558,  0.34415584, -0.36363636],
       [-0.44805195,  0.03246753,  0.17532468, -0.09090909],
       [-0.66883117,  0.01948052,  0.30519481, -0.45454545]])

In [ ]:
np.linalg.pinv(A) # uogólniona metoda odwarcania macierzy (Moore-Penrose pseudo-inverse)

array([[ 1.42207792,  0.2012987 , -0.51298701,  0.63636364],
       [-0.43506494, -0.08441558,  0.34415584, -0.36363636],
       [-0.44805195,  0.03246753,  0.17532468, -0.09090909],
       [-0.66883117,  0.01948052,  0.30519481, -0.45454545]])

$A^{-1}  A = I$

In [ ]:
np.linalg.inv(A) @ A

array([[ 1.00000000e+00, -6.66133815e-16, -4.44089210e-16,
         4.44089210e-16],
       [ 0.00000000e+00,  1.00000000e+00,  1.11022302e-16,
        -2.22044605e-16],
       [ 0.00000000e+00,  4.16333634e-17,  1.00000000e+00,
        -5.55111512e-17],
       [ 0.00000000e+00,  1.66533454e-16, -1.66533454e-16,
         1.00000000e+00]])

In [ ]:
np.round(np.abs(np.linalg.inv(A) @ A))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Rozwiązanie 1.5

In [ ]:
A @ A @ A

array([[ -15,   51,   38,  -98],
       [ 190,   94,  111,  261],
       [ 151,  241,  341, -109],
       [ 103,   38,  158,   69]])

In [ ]:
np.linalg.matrix_power(A, 3)

array([[ -15,   51,   38,  -98],
       [ 190,   94,  111,  261],
       [ 151,  241,  341, -109],
       [ 103,   38,  158,   69]])

In [ ]:
A**3 ## podniesienie do 3 potęgi wszystkich elementów macierzy

array([[  1,   8,  -1,   0],
       [ 27,  -8,  64, 125],
       [  8, 216, 125, -27],
       [  0,   1, 125, -64]])

In [ ]:
np.power(A, 3)

array([[  1,   8,  -1,   0],
       [ 27,  -8,  64, 125],
       [  8, 216, 125, -27],
       [  0,   1, 125, -64]])

Zadanie 6. Niech A będzie macierzą z następującymi elementami

$$
A = 
\begin{pmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{pmatrix}
$$

In [ ]:
dane = np.arange(1, 10)
dane

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
A5 = dane.reshape(3,3, order = 'C')
A5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

1. Wyznacz liczbę wierszy i kolumn macierzy A.
2. Wyznacz sumę wszystkich elementów macierzy A.
3. Wyznacz sumy wszytkich elementów w poszczególnych kolumnach macierzy
A.
4. Wyznacz sumy wszytkich elementów w poszczególnych wierszach macierzy A.
5. Wyznacz średnie wszytkich elementów w poszczególnych kolumnach macierzy
A.
6. Wyznacz średnie wszytkich elementów w poszczególnych wierszach macierzy
A.
7. Oblicz A11 + A32.
8. Wyświetl zawartość drugiej kolumny.
9. Wyświetl zawartość pierwszego wiersza.

In [ ]:
A5.shape ## np.shape(A5) 5.1
A5.sum() ## np.sum(A5) 5.2
A5.sum(axis = 0) ## np.sum(A5, axis = 0) 5.3
A5.sum(axis = 1) ## np.sum(A5, axis = 1) 5.4
A5.mean(axis = 0) ## np.mean(A5, axis = 0) 5.5
A5.mean(axis = 1) ## np.mean(A5, axis = 1) 5.6
A5[0,0] + A5[2,1] ## 5.7
A5[0][0] + A5[2][1] ## podobne do C/ C++ 5.7
A5[:, 1] ## druga kolumna 5.8
A5[0, :] ## A5[0] 5.8

array([1, 2, 3])

Deklaracje różnych ważnych macierzy.

In [ ]:
print(np.zeros([3,3]))
print(np.zeros([3,3], dtype = int))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
np.ones([3,3])
np.ones([3,3], dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.eye(3) ## macierz jednostkowa
np.eye(3, dtype = int) ## macierz jednostkowa

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
zera = np.zeros([3,3])
zera[1,1] = 3
zera

array([[0., 0., 0.],
       [0., 3., 0.],
       [0., 0., 0.]])

In [ ]:
zera_int = np.zeros([3,3], dtype = int)
zera_int[1,1] = 3.6
zera_int

array([[0, 0, 0],
       [0, 3, 0],
       [0, 0, 0]])